version: '3.1'

services:
  pipeline:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./config.toml:/usr/share/nginx/html/config.toml
      - ./certificates:/etc/certificates
    environment:
      - NGINX_HOST=localhost
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend
  pipeline-ssl:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./config.toml:/usr/share/nginx/html/config.toml
      - ./certificates:/etc/certificates
    environment:
      - NGINX_HOST=localhost
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default-ssl.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend
networks:
  backend:
    driver: bridge
